osx_instance:
  image: mojave-xcode-11.2.1-flutter
#  image: mojave-xcode-10.1-flutter

unit_task:
  pub_script:
    - pub --version
    - dart --version
    - pub get # because no pubspec.lock
  test_script:
    - pub run test test/all_tests.dart

integration_task:
  simulators_script: xcrun simctl list devices --json
  doctor_script: flutter doctor -v
  activate_script: pub global activate --source path .
  imagemagick_script: brew install imagemagick
  test_script:
    - export PATH="$HOME/.pub-cache/bin:$PATH" # needed to find screenshots
    - cd example
    - screenshots -c screenshots_ios.yaml -v