name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators and simulators with support for locales. Compatible with fastlane for upload to both stores.
version: 1.3.0
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  args: ^1.5.1
  yaml: ^2.1.15
  resource: ^2.1.5
  path: ^1.6.2
  file: ^5.0.7
  archive: ^2.0.9
  platform: ^2.2.0
  process: ^3.0.9
  meta: ^1.1.6
  intl: ^0.15.8

dev_dependencies:
  test: ^1.5.1+1
  test_api: ^0.2.5
  mockito: ^4.1.0
  pedantic: ^1.8.0+1
  quiver: '>=2.0.0 <3.0.0'

executables:
  screenshots: main