name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators and simulators. Compatible with fastlane for upload to both stores
version: 0.0.2
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  args: ^1.5.1
  file_utils: ^0.1.1
  yaml: ^2.1.15
  resource: ^2.1.5
#  convert: ^2.1.1
#  convert: ^2.0.2
  path: ^1.6.2

dev_dependencies:
#  test: ^1.0.0
  test: ^1.5.1+1

#  flutter_test:
#    sdk: flutter
#  flutter_driver:
#    sdk: flutter

executables:
  screenshots: main